In [102]:
import pandas as pd
import numpy as np

In [103]:
dftrain = pd.read_excel("C:\\Users\\Viswes\\hackathon\\AICTE3 datasets\\AICTE train.xlsx")

In [104]:
dftrain.head()

YEAR          STATE            CITY  CITY ID LEVEL  \
0  2015  Andhra Pradesh  Visakhapatnam        1    UG   
1  2016  Andhra Pradesh  Visakhapatnam        1    UG   
2  2017  Andhra Pradesh  Visakhapatnam        1    UG   
3  2015  Andhra Pradesh  Visakhapatnam        1    UG   
4  2016  Andhra Pradesh  Visakhapatnam        1    UG   

                   PROGRAMME                           COURSE  COURSE ID  \
0  Engineering and Technolgy  Computer Science and Technology          1   
1  Engineering and Technolgy  Computer Science and Technology          1   
2  Engineering and Technolgy  Computer Science and Technology          1   
3  Engineering and Technolgy  Computer Science and Technology          1   
4  Engineering and Technolgy  Computer Science and Technology          1   

   CUTOFF LOG10  COLLEGE RANK  INTAKE  ENROLLED STUDENTS  PLACED STUDENTS  \
0          3.54             3     120                126               84   
1          3.50             3     240                235               98   
2          3.66             3     240                244               91   
3          3.78             3     120                119               68   
4          3.91             3     180                176               76   

   CUTOFF RANK  
0         3490  
1         3193  
2         4601  
3         6049  
4         8172

In [105]:
dftrain.drop(['CITY','CITY ID','LEVEL','PROGRAMME','COURSE','COURSE ID','STATE ','PLACED STUDENTS'],axis=1,inplace=True)


In [106]:
#dftrain.drop([3,4,5],axis=0,inplace =True)

In [107]:
dftrain.head()

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE  ENROLLED STUDENTS  CUTOFF RANK
0  2015          3.54             3     120                126         3490
1  2016          3.50             3     240                235         3193
2  2017          3.66             3     240                244         4601
3  2015          3.78             3     120                119         6049
4  2016          3.91             3     180                176         8172

In [108]:
X = dftrain.iloc[:,0:4]
y = dftrain.iloc[:,4]

In [109]:
X

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE
0   2015          3.54             3     120
1   2016          3.50             3     240
2   2017          3.66             3     240
3   2015          3.78             3     120
4   2016          3.91             3     180
5   2017          3.69             3     180
6   2015          5.11             6     120
7   2016          5.07             6     120
8   2017          4.81             6     120
9   2015          5.12             5     120
10  2016          5.09             5     180
11  2017          4.79             5     180
12  2015          5.10             4     180
13  2016          4.74             4     180
14  2017          4.83             4     180
15  2015          5.12             6     120
16  2016          4.96             6     120
17  2017          5.11             6     120

In [110]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X,y)

LinearRegression()

In [111]:
dftest = pd.read_excel("C:\\Users\\Viswes\\hackathon\\AICTE3 datasets\\AICTE3 test.xlsx")

In [112]:
dftest.drop(['CITY','CITY ID','LEVEL','PROGRAMME','COURSE','COURSE ID','STATE ','PLACED STUDENTS'],axis=1,inplace=True)


In [113]:
#dftest.drop(2,axis=0,inplace=True)
dftest.drop(4,axis=0,inplace=True)

In [114]:
X_test = dftest.iloc[:,0:4]
y_test = dftest.iloc[:,4]

In [115]:
y_pred = reg.predict(X_test)

In [116]:
dftest.head()

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE  ENROLLED STUDENTS  CUTOFF RANK
0  2018          3.47             3     240                234         2985
1  2018          3.69             3     180                179         4870
2  2018          4.77             6     120                104        58707
3  2018          4.79             5     180                130        61550
4  2018          4.81             4     180                 53        65016

In [117]:
y_pred

array([251.004818  , 178.33700544,  84.17735438, 123.26399751,
       106.70293965,  69.47816711])

In [118]:
y_test

0    234
1    179
2    104
3    130
4     53
5     95
Name: ENROLLED STUDENTS, dtype: int64

In [119]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print('mae=',mean_absolute_error(y_test,y_pred))
print('mse=',mean_squared_error(y_test,y_pred))
print('r2_score=',r2_score(y_test,y_pred))

mae= 20.575205536202702
mse= 710.5473478466339
r2_score= 0.797078269969309


In [120]:
dftrain

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE  ENROLLED STUDENTS  CUTOFF RANK
0   2015          3.54             3     120                126         3490
1   2016          3.50             3     240                235         3193
2   2017          3.66             3     240                244         4601
3   2015          3.78             3     120                119         6049
4   2016          3.91             3     180                176         8172
5   2017          3.69             3     180                179         4870
6   2015          5.11             6     120                 49       129514
7   2016          5.07             6     120                 58       116172
8   2017          4.81             6     120                 59        64219
9   2015          5.12             5     120                 51       130708
10  2016          5.09             5     180                130       124267
11  2017          4.79             5     180                130        61550
12  2015          5.10             4     180                 75       126894
13  2016          4.74             4     180                 75        55326
14  2017          4.83             4     180                 90        68172
15  2015          5.12             6     120                 47       130716
16  2016          4.96             6     120                 70        90652
17  2017          5.11             6     120                 70       129287

In [121]:
reg.intercept_

-2157.791812061869

In [122]:
reg.coef_

array([  1.19406248, -77.36414355,  15.01377499,   0.92746168])

In [123]:
X

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE
0   2015          3.54             3     120
1   2016          3.50             3     240
2   2017          3.66             3     240
3   2015          3.78             3     120
4   2016          3.91             3     180
5   2017          3.69             3     180
6   2015          5.11             6     120
7   2016          5.07             6     120
8   2017          4.81             6     120
9   2015          5.12             5     120
10  2016          5.09             5     180
11  2017          4.79             5     180
12  2015          5.10             4     180
13  2016          4.74             4     180
14  2017          4.83             4     180
15  2015          5.12             6     120
16  2016          4.96             6     120
17  2017          5.11             6     120

In [124]:
y

0     126
1     235
2     244
3     119
4     176
5     179
6      49
7      58
8      59
9      51
10    130
11    130
12     75
13     75
14     90
15     47
16     70
17     70
Name: ENROLLED STUDENTS, dtype: int64

In [125]:
X23 = np.array([2020,np.log10(90937),6,120])
X23=X23.reshape(1, 4)

In [126]:
y23p = reg.predict(X23)

In [127]:
y23p

array([71.9637227])

In [128]:
X_test

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE
0  2018          3.47             3     240
1  2018          3.69             3     180
2  2018          4.77             6     120
3  2018          4.79             5     180
4  2018          4.81             4     180
5  2018          4.96             6     120

In [1]:
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, LassoCV, LassoLarsCV, ElasticNet, Lasso
from sklearn.preprocessing import scale, MinMaxScaler
import pickle
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn import linear_model

In [130]:
#svm-worst fit
svm_clf = svm.SVR()
svm_clf.fit(X,y)
ysvm_pred=svm_clf.predict(X_test)
print('mae=',mean_absolute_error(y_test,ysvm_pred))
print('mse=',mean_squared_error(y_test,ysvm_pred))
print('r2_score=',r2_score(y_test,ysvm_pred))

mae= 59.836228420174656
mse= 6000.903711590523
r2_score= -0.7137686413071771


In [131]:
#random forests
rand_clf=RandomForestRegressor(n_estimators = 1000,max_features='sqrt')
rand_clf.fit(X,y)
yrand_pred=rand_clf.predict(X_test)
print('mae=',mean_absolute_error(y_test,yrand_pred))
print('mse=',mean_squared_error(y_test,yrand_pred))
print('r2_score=',r2_score(y_test,yrand_pred))

mae= 20.5795
mse= 647.9450151666668
r2_score= 0.8149565629358146


In [132]:
#lasso
lasso_clf = linear_model.Lasso(alpha=0.001, selection="random", random_state=1)
lasso_clf.fit(X,y)
ylasso_pred=lasso_clf.predict(X_test)
print('mae=',mean_absolute_error(y_test,ylasso_pred))
print('mse=',mean_squared_error(y_test,ylasso_pred))
print('r2_score=',r2_score(y_test,ylasso_pred))

mae= 20.576936831469386
mse= 710.7211820287289
r2_score= 0.797028625518343


In [133]:
#ridge -best fit
ridge_clf = Ridge(alpha=0.1)
ridge_clf.fit(X,y)
yridge_pred=ridge_clf.predict(X_test)
print('mae=',mean_absolute_error(y_test,yridge_pred))
print('mse=',mean_squared_error(y_test,yridge_pred))
print('r2_score=',r2_score(y_test,yridge_pred))

mae= 20.68956333462438
mse= 764.9220493957705
r2_score= 0.7815496658000132


In [134]:
yrand_pred

array([225.07 , 176.4  ,  77.341, 120.013,  99.471,  66.17 ])

In [135]:
yridge_pred

array([249.4276628 , 178.9110217 ,  83.58886039, 124.13779589,
       110.14217898,  69.79478379])

In [136]:
y_test

0    234
1    179
2    104
3    130
4     53
5     95
Name: ENROLLED STUDENTS, dtype: int64