In [71]:
import pandas as pd
import numpy as np

In [72]:
dftrain = pd.read_excel("C:\\Users\\Viswes\\hackathon\\AICTE3 datasets\\AICTE train.xlsx")

In [73]:
dftrain.head()

YEAR          STATE            CITY  CITY ID LEVEL  \
0  2015  Andhra Pradesh  Visakhapatnam        1    UG   
1  2016  Andhra Pradesh  Visakhapatnam        1    UG   
2  2017  Andhra Pradesh  Visakhapatnam        1    UG   
3  2015  Andhra Pradesh  Visakhapatnam        1    UG   
4  2016  Andhra Pradesh  Visakhapatnam        1    UG   

                   PROGRAMME                           COURSE  COURSE ID  \
0  Engineering and Technolgy  Computer Science and Technology          1   
1  Engineering and Technolgy  Computer Science and Technology          1   
2  Engineering and Technolgy  Computer Science and Technology          1   
3  Engineering and Technolgy  Computer Science and Technology          1   
4  Engineering and Technolgy  Computer Science and Technology          1   

   CUTOFF LOG10  COLLEGE RANK  INTAKE  ENROLLED STUDENTS  PLACED STUDENTS  \
0          3.54             3     120                126               84   
1          3.50             3     240                235               98   
2          3.66             3     240                244               91   
3          3.78             3     120                119               68   
4          3.91             3     180                176               76   

   CUTOFF RANK  
0         3490  
1         3193  
2         4601  
3         6049  
4         8172

In [74]:
dftrain.drop(['CITY','CITY ID','LEVEL','PROGRAMME','COURSE','COURSE ID','STATE ','PLACED STUDENTS'],axis=1,inplace=True)


In [75]:
#dftrain.drop([3,4,5],axis=0,inplace =True)

In [76]:
dftrain.head()

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE  ENROLLED STUDENTS  CUTOFF RANK
0  2015          3.54             3     120                126         3490
1  2016          3.50             3     240                235         3193
2  2017          3.66             3     240                244         4601
3  2015          3.78             3     120                119         6049
4  2016          3.91             3     180                176         8172

In [77]:
X = dftrain.iloc[:,0:4]
y = dftrain.iloc[:,4]

In [78]:
X

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE
0   2015         3.540             3     120
1   2016         3.500             3     240
2   2017         3.660             3     240
3   2015         3.780             3     120
4   2016         3.910             3     180
5   2017         3.690             3     180
6   2015         5.110             6     120
7   2016         5.070             6     120
8   2017         4.810             6     120
9   2015         5.120             5     120
10  2016         5.090             5     180
11  2017         4.790             5     180
12  2015         5.100             4     180
13  2016         4.740             4     180
14  2017         4.830             4     180
15  2015         5.120             6     120
16  2016         4.960             6     120
17  2017         5.110             6     120
18  2015         4.660             3     240
19  2018         4.200             3     240
20  2017         4.480             3     240
21  2015         4.400             2      60
22  2016         4.800             2      60
23  2017         4.590             2      50
24  2015         4.358             3     120
25  2016         4.973             3     120
26  2017         4.967             3     120

In [79]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X,y)

LinearRegression()

In [80]:
dftest = pd.read_excel("C:\\Users\\Viswes\\hackathon\\AICTE3 datasets\\AICTE3 test.xlsx")

In [81]:
dftest.drop(['CITY','CITY ID','LEVEL','PROGRAMME','COURSE','COURSE ID','STATE ','PLACED STUDENTS'],axis=1,inplace=True)


In [82]:
#dftest.drop(2,axis=0,inplace=True)
#dftest.drop(4,axis=0,inplace=True)

In [83]:
X_test = dftest.iloc[:,0:4]
y_test = dftest.iloc[:,4]

In [84]:
y_pred = reg.predict(X_test)

In [85]:
dftest.head()

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE  ENROLLED STUDENTS  CUTOFF RANK
0  2018          3.47             3     240                234         2985
1  2018          3.69             3     180                179         4870
2  2018          4.77             6     120                104        58707
3  2018          4.79             5     180                130        61550
4  2018          4.81             4     180                 53        65016

In [86]:
y_pred

array([249.83216001, 192.19669625,  76.42534018, 133.51855694,
       141.29768927,  69.2386944 ,  93.1056337 , 183.04688341,
        55.68243869])

In [87]:
y_test

0    234
1    179
2    104
3    130
4     53
5     95
6    114
7     80
8     40
Name: ENROLLED STUDENTS, dtype: int64

In [88]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print('mae=',mean_absolute_error(y_test,y_pred))
print('mse=',mean_squared_error(y_test,y_pred))
print('r2_score=',r2_score(y_test,y_pred))

mae= 34.86719514423102
mse= 2328.761399235747
r2_score= 0.2941721360166457


In [89]:
dftrain

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE  ENROLLED STUDENTS  CUTOFF RANK
0   2015         3.540             3     120                126         3490
1   2016         3.500             3     240                235         3193
2   2017         3.660             3     240                244         4601
3   2015         3.780             3     120                119         6049
4   2016         3.910             3     180                176         8172
5   2017         3.690             3     180                179         4870
6   2015         5.110             6     120                 49       129514
7   2016         5.070             6     120                 58       116172
8   2017         4.810             6     120                 59        64219
9   2015         5.120             5     120                 51       130708
10  2016         5.090             5     180                130       124267
11  2017         4.790             5     180                130        61550
12  2015         5.100             4     180                 75       126894
13  2016         4.740             4     180                 75        55326
14  2017         4.830             4     180                 90        68172
15  2015         5.120             6     120                 47       130716
16  2016         4.960             6     120                 70        90652
17  2017         5.110             6     120                 70       129287
18  2015         4.660             3     240                207        45486
19  2018         4.200             3     240                244        15929
20  2017         4.480             3     240                206        30121
21  2015         4.400             2      60                 60        25176
22  2016         4.800             2      60                 56        63567
23  2017         4.590             2      50                 27        39025
24  2015         4.358             3     120                114        22803
25  2016         4.973             3     120                112        93952
26  2017         4.967             3     120                109        92690

In [90]:
reg.intercept_

-12195.646740395377

In [91]:
reg.coef_

array([  6.1472152 , -37.82445146,  -8.53562135,   0.82190141])

In [92]:
X

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE
0   2015         3.540             3     120
1   2016         3.500             3     240
2   2017         3.660             3     240
3   2015         3.780             3     120
4   2016         3.910             3     180
5   2017         3.690             3     180
6   2015         5.110             6     120
7   2016         5.070             6     120
8   2017         4.810             6     120
9   2015         5.120             5     120
10  2016         5.090             5     180
11  2017         4.790             5     180
12  2015         5.100             4     180
13  2016         4.740             4     180
14  2017         4.830             4     180
15  2015         5.120             6     120
16  2016         4.960             6     120
17  2017         5.110             6     120
18  2015         4.660             3     240
19  2018         4.200             3     240
20  2017         4.480             3     240
21  2015         4.400             2      60
22  2016         4.800             2      60
23  2017         4.590             2      50
24  2015         4.358             3     120
25  2016         4.973             3     120
26  2017         4.967             3     120

In [93]:
y

0     126
1     235
2     244
3     119
4     176
5     179
6      49
7      58
8      59
9      51
10    130
11    130
12     75
13     75
14     90
15     47
16     70
17     70
18    207
19    244
20    206
21     60
22     56
23     27
24    114
25    112
26    109
Name: ENROLLED STUDENTS, dtype: int64

In [94]:
X23 = np.array([2020,np.log10(90937),6,120])
X23=X23.reshape(1, 4)

In [95]:
y23p = reg.predict(X23)

In [96]:
y23p

array([81.58076005])

In [97]:
X_test

YEAR  CUTOFF LOG10  COLLEGE RANK  INTAKE
0  2018         3.470             3     240
1  2018         3.690             3     180
2  2018         4.770             6     120
3  2018         4.790             5     180
4  2018         4.810             4     180
5  2018         4.960             6     120
6  2018         5.006             3     120
7  2018         5.010             4     240
8  2018         4.700             2      50

In [98]:
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, LassoCV, LassoLarsCV, ElasticNet, Lasso
from sklearn.preprocessing import scale, MinMaxScaler
import pickle
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn import linear_model

In [99]:
#svm-worst fit
svm_clf = svm.SVR()
svm_clf.fit(X,y)
ysvm_pred=svm_clf.predict(X_test)
print('mae=',mean_absolute_error(y_test,ysvm_pred))
print('mse=',mean_squared_error(y_test,ysvm_pred))
print('r2_score=',r2_score(y_test,ysvm_pred))

mae= 43.769373099212416
mse= 3325.393978377259
r2_score= -0.007898760874093469


In [100]:
#random forests
rand_clf=RandomForestRegressor(n_estimators = 1000,max_features='sqrt')
rand_clf.fit(X,y)
yrand_pred=rand_clf.predict(X_test)
print('mae=',mean_absolute_error(y_test,yrand_pred))
print('mse=',mean_squared_error(y_test,yrand_pred))
print('r2_score=',r2_score(y_test,yrand_pred))

mae= 24.134777777777778
mse= 1214.9629876666665
r2_score= 0.6317550047484342


In [101]:
#lasso
lasso_clf = linear_model.Lasso(alpha=0.001, selection="random", random_state=1)
lasso_clf.fit(X,y)
ylasso_pred=lasso_clf.predict(X_test)
print('mae=',mean_absolute_error(y_test,ylasso_pred))
print('mse=',mean_squared_error(y_test,ylasso_pred))
print('r2_score=',r2_score(y_test,ylasso_pred))

mae= 34.866207099268244
mse= 2328.7557617673588
r2_score= 0.2941738446855853


In [102]:
#ridge -best fit
ridge_clf = Ridge(alpha=0.1)
ridge_clf.fit(X,y)
yridge_pred=ridge_clf.predict(X_test)
print('mae=',mean_absolute_error(y_test,yridge_pred))
print('mse=',mean_squared_error(y_test,yridge_pred))
print('r2_score=',r2_score(y_test,yridge_pred))

mae= 34.836085755200756
mse= 2341.1228897196365
r2_score= 0.2904254729077682


In [103]:
yrand_pred

array([236.136, 179.453,  75.6  , 120.701, 101.176,  73.031, 109.373,
       162.654,  59.499])

In [104]:
yridge_pred

array([249.22185868, 191.60367689,  76.04852493, 133.48662158,
       141.44893495,  69.0164535 ,  93.42154623, 183.52253778,
        55.72766657])

In [105]:
y_test

0    234
1    179
2    104
3    130
4     53
5     95
6    114
7     80
8     40
Name: ENROLLED STUDENTS, dtype: int64